version: '3'
services:

  frontend:
    container_name: frontend
    image: fortune-cookie-frontend:latest
    environment:
      - BACKEND_DNS=backend
    restart: always
    ports:
      - "8080:8080"

  backend:
    container_name: backend
    image: fortune-cookie-backend:latest
    restart: always
