version: '3'
services:

  frontend:
    container_name: frontend
    build: frontend/
    restart: always
    ports:
      - "8080:8080"

  backend:
    container_name: backend
    build: backend/
    restart: always
    ports:
      - "9000:9000"
    

    