version: '3'
services:

  frontend:
    container_name: frontend
    build: frontend/
    environment:
      - BACKEND_DNS=backend
    restart: always
    ports:
      - "8080:8080"

  backend:
    container_name: backend
    build: backend/
    restart: always
