apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: janiksunke/fortune-cookie-frontend:$TAG
          name: frontend
          env:
          - name: BACKEND_DNS
            value: backend
          - name: BACKEND_PORT
            value: "9000"