name: PRODUCTION CI 
on:
  push:
    branches:
      - "main"
jobs:
  Clone-down-upload:
    runs-on: Production
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Docker-build-run:
    runs-on: Production
    needs: Clone-down-upload
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: code
          path: . | !.git
      - name: setup
        run: chmod +x ./runapp.sh && ./runapp.sh