name: PRODUCTION CI
on:
  push:
    branches:
      - "main"
jobs:
  Clone-down-upload:
    runs-on: Production
    container: golang:1.16
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Docker-build-run:
    runs-on: Production
    needs: Clone-down-upload
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: setup
        run: source ci/runapp.sh