name: STAGING CI
on: pull_request
jobs:
  Clone-down-upload:
    runs-on: Production
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Docker-build-run:
    runs-on: Production
    needs: Clone-down-upload
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: setup
        run: chmod +x ./runapp.sh && ./runapp.sh
  Functional-test:
    runs-on: Production
    needs: Docker-build-run
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Test
        run: echo "test"
  Docker-down:
    runs-on: Production
    needs: Functional-test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: setup
        run: chmod +x ./runapp.sh && ./downapp.sh